services:
  picvoter-service:
    image: ${DOCKER_IMAGE_TAG}
    container_name: ${DOCKER_CONTAINER_NAME}
    restart: unless-stopped
    ports:
      - "9988:8080"
    depends_on:
      - redis-picvoter
    volumes:
      - ${PICTURES_BASE_PATH}:/media/pictures-data
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - PictureProviders__Default=ig
      - RedistHost=redis-picvoter,password=${REDIS_PASS}
      - HOSTNAME=${HOSTNAME}

  # The Redis database service.
  redis-picvoter:
    image: redis
    container_name: ${DOCKER_REDIS_CONTAINER_NAME}
    restart: unless-stopped
    ports:
      - "${REDIS_HOST_PORT}:6379"
    volumes:
      - redis-picvoter-data:/data
    command: redis-server --save 10 1 --loglevel warning --requirepass ${REDIS_PASS}
    
  mysql_db:
    image: mysql:latest
    container_name: my-mysql-container
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  redis-picvoter-data:
  mysql_data:
