services:
  picvoter-service:
    image: ${DOCKER_IMAGE_TAG}
    container_name: ${DOCKER_CONTAINER_NAME}
    restart: unless-stopped
    ports:
      - "9988:4430"
    depends_on:
      - redis-picvoter
    volumes:
      - ${PICTURES_BASE_PATH}:/media/pictures-data
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - PictureProviders__Default=ig
      - RedistHost=redis-picvoter,password=${REDIS_PASS}
      - HOSTNAME=${HOSTNAME}

  # The Redis database service.
  redis-picvoter:
    image: redis
    container_name: ${DOCKER_REDIS_CONTAINER_NAME}
    restart: unless-stopped
    ports:
      - "${REDIS_HOST_PORT}:6379"
    volumes:
      - redis-picvoter-data:/data
    command: redis-server --save 10 1 --loglevel warning --requirepass ${REDIS_PASS}

volumes:
  redis-picvoter-data:
